# Generated by Django 3.1.3 on 2020-11-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieonelinecomment_moviereview_moviereviewcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieOnelineComment',
            new_name='MovieOneline',
        ),
    ]
