# Generated by Django 3.1.3 on 2020-11-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201120_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieoneline',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_onelines', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviereviewcomment',
            name='movie_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_review_comments', to='movies.moviereview'),
        ),
    ]
