# Generated by Django 3.1.3 on 2020-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('popularity', models.FloatField()),
                ('video', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('original_language', models.CharField(max_length=2)),
                ('original_title', models.CharField(max_length=100)),
                ('backdrop_path', models.TextField(blank=True)),
                ('adult', models.BooleanField(default=False)),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(related_name='genres', to='data.Movie')),
            ],
        ),
    ]
